// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rest_network.proto

#ifndef PROTOBUF_rest_5fnetwork_2eproto__INCLUDED
#define PROTOBUF_rest_5fnetwork_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace rest_network {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_rest_5fnetwork_2eproto();
void protobuf_AssignDesc_rest_5fnetwork_2eproto();
void protobuf_ShutdownFile_rest_5fnetwork_2eproto();

class ControlNetworkData;

// ===================================================================

class ControlNetworkData : public ::google::protobuf::Message {
 public:
  ControlNetworkData();
  virtual ~ControlNetworkData();

  ControlNetworkData(const ControlNetworkData& from);

  inline ControlNetworkData& operator=(const ControlNetworkData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ControlNetworkData& default_instance();

  void Swap(ControlNetworkData* other);

  // implements Message ----------------------------------------------

  ControlNetworkData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ControlNetworkData& from);
  void MergeFrom(const ControlNetworkData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required sint32 left = 1;
  inline bool has_left() const;
  inline void clear_left();
  static const int kLeftFieldNumber = 1;
  inline ::google::protobuf::int32 left() const;
  inline void set_left(::google::protobuf::int32 value);

  // required sint32 right = 2;
  inline bool has_right() const;
  inline void clear_right();
  static const int kRightFieldNumber = 2;
  inline ::google::protobuf::int32 right() const;
  inline void set_right(::google::protobuf::int32 value);

  // required int32 mode = 3;
  inline bool has_mode() const;
  inline void clear_mode();
  static const int kModeFieldNumber = 3;
  inline ::google::protobuf::int32 mode() const;
  inline void set_mode(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:rest_network.ControlNetworkData)
 private:
  inline void set_has_left();
  inline void clear_has_left();
  inline void set_has_right();
  inline void clear_has_right();
  inline void set_has_mode();
  inline void clear_has_mode();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 left_;
  ::google::protobuf::int32 right_;
  ::google::protobuf::int32 mode_;
  friend void  protobuf_AddDesc_rest_5fnetwork_2eproto();
  friend void protobuf_AssignDesc_rest_5fnetwork_2eproto();
  friend void protobuf_ShutdownFile_rest_5fnetwork_2eproto();

  void InitAsDefaultInstance();
  static ControlNetworkData* default_instance_;
};
// ===================================================================


// ===================================================================

// ControlNetworkData

// required sint32 left = 1;
inline bool ControlNetworkData::has_left() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ControlNetworkData::set_has_left() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ControlNetworkData::clear_has_left() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ControlNetworkData::clear_left() {
  left_ = 0;
  clear_has_left();
}
inline ::google::protobuf::int32 ControlNetworkData::left() const {
  // @@protoc_insertion_point(field_get:rest_network.ControlNetworkData.left)
  return left_;
}
inline void ControlNetworkData::set_left(::google::protobuf::int32 value) {
  set_has_left();
  left_ = value;
  // @@protoc_insertion_point(field_set:rest_network.ControlNetworkData.left)
}

// required sint32 right = 2;
inline bool ControlNetworkData::has_right() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ControlNetworkData::set_has_right() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ControlNetworkData::clear_has_right() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ControlNetworkData::clear_right() {
  right_ = 0;
  clear_has_right();
}
inline ::google::protobuf::int32 ControlNetworkData::right() const {
  // @@protoc_insertion_point(field_get:rest_network.ControlNetworkData.right)
  return right_;
}
inline void ControlNetworkData::set_right(::google::protobuf::int32 value) {
  set_has_right();
  right_ = value;
  // @@protoc_insertion_point(field_set:rest_network.ControlNetworkData.right)
}

// required int32 mode = 3;
inline bool ControlNetworkData::has_mode() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ControlNetworkData::set_has_mode() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ControlNetworkData::clear_has_mode() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ControlNetworkData::clear_mode() {
  mode_ = 0;
  clear_has_mode();
}
inline ::google::protobuf::int32 ControlNetworkData::mode() const {
  // @@protoc_insertion_point(field_get:rest_network.ControlNetworkData.mode)
  return mode_;
}
inline void ControlNetworkData::set_mode(::google::protobuf::int32 value) {
  set_has_mode();
  mode_ = value;
  // @@protoc_insertion_point(field_set:rest_network.ControlNetworkData.mode)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace rest_network

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_rest_5fnetwork_2eproto__INCLUDED
